dataset_path: "KEEL/keel_data/phoneme.dat"

seeds: [17, 42, 123, 27, 2727, 32]

noise_scale: 1.1
label_noise_scale: 0.0
noise_type: "gaussian"

models:
  pdrf:
    n_cascade_estimators: 4
    n_trees_pdrf: 20
    max_depth_pdrf: 10
  rf:
    n_estimators: 100
  deep_forest:
    n_estimators: 2
    n_trees_drf: 20

  neural_network:
    epochs: 20
    batch_size: 64
    hidden_units: 64
    dropout_rate: 0.5
    optimizer: "adam"
  ksvm: {}         # Empty config is valid
  prf:             # ← Fix this line!
    n_estimators: 10
    bootstrap: true
