name: "wine-quiality-red"
dataset_path: "KEEL/keel_data/winequality-red.dat"

seeds: [17, 42, 123, 27, 2727, 32]

noise_scale: 1.5
noise_type: "gaussian"
label_noise_scale: 0.2
label_noise_range: [0.0, 0.5]

models:
  pdrf:
    n_cascade_estimators: 4
    n_trees_pdrf: 20
    max_depth_pdrf: 4

  rf:
    n_estimators: 20

  deep_forest:
    n_estimators: 2
    n_trees_drf: 20

  prf:             # ← Fix this line!
    n_estimators: 20
    bootstrap: true
